# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := usbus enumerator

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

usbus: 
	@echo "==== Building usbus ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f usbus.make

enumerator: usbus
	@echo "==== Building enumerator ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f enumerator.make

clean:
	@${MAKE} --no-print-directory -C . -f usbus.make clean
	@${MAKE} --no-print-directory -C . -f enumerator.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   usbus"
	@echo "   enumerator"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
